name: Deploy CDN

on:
  push:
    branches:
      - main
      - releases/*
      - devops-to-github-action
    # paths:
    #   - "!.github/**"
    #   - "!.devops/**"
    #   - "!infra/**"
    #   - "!.pre-commit-config.yaml"
    #   - "!.terraform-version"
    #   - "!CODEOWNERS"
  
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options: 
        - dev
        - uat
        - prod

        
jobs:
  release_and_deploy:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_cdn.yml@devops-to-github-action
    name: 'login frontend'
    secrets: inherit
    with:
      environment: ${{ inputs.env != null && inputs.env || (startsWith(github.ref_name, 'releases/') && 'uat') || 'dev' }}
      storage_account_name: "checkoutsa"
      profile_name: checkout-cdn-profile
      endpoint_name: checkout-cdn-endpoint
      resource_group_name: checkout-fe-rg
      blob_container_name: "$web"
      base_path: auth

  promote_release:
    name: 'Promote prerelase release'
    if: ${{ inputs.env == 'prod' }}
    runs-on: ubuntu-20.04
    needs: [release_and_deploy]
    steps:
      - uses:  pagopa/selfcare-commons/github-actions-template/promote-release@main
        with:
          github_path_token: ${{ secrets.GH_PAT_VARIABLES }}
          release_version: ${{ vars.CURRENT_UAT_VERSION }}
